models.py
from app import db 
import datetime 
from config import Configuration 
import re

# class Test(db.Model):
#     id = db.Column(db.Integer,primary_key=True)
#     name = db.Column(db.String(80))

#     def __init__(self,*args,**kwargs):
#         super(Test,self).__init__(*args,**kwargs)

# def slugify(name):
#     return re.sub('[^\w]+','-',name).lower()


class Person(db.Model):


	
    id = db.Column(db.Integer,primary_key=True)
    image_id = db.Column(db.String(20),nullable=False)
    name = db.Column(db.String(60),unique=True,nullable=False)
    slug = db.Column(db.String(60),unique=True)
    person_type = db.Column(db.String(50),nullable=False)
    biography = db.Column(db.Text,nullable=False)
    created_timestamp = db.Column(db.DateTime,default=datetime.datetime.now())
    rating = db.Column(db.Float,default=0.0)


    def __init__(self,*args,**kwargs):
        super(Person,self).__init__(*args,**kwargs)
        

    def read_more(self):
        return self.biography[:42] + " ..."
        

app.py
from flask import Flask 
from config import Configuration 
from flask_sqlalchemy import SQLAlchemy 
from flask_migrate import Migrate , MigrateCommand 
from flask_script import Manager 

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)
migrate = Migrate(app,db)

manager = Manager(app)

manager.add_command('db',MigrateCommand)

bns_leader/bns_blueprint.py
from flask import Blueprint, url_for, render_template, request, redirect, flash, g
from models import Person

bns_blueprint = Blueprint('bns_leader',__name__,template_folder='templates')


def object_list(template,query):

	if request.args.get('q'):
		search = request.args['q']
		query = query.filter(Person.name.contains(search))
	return render_template(template,persons=query)


@bns_blueprint.route('/')
def bns_home():

	persons = Person.query.filter(
		Person.person_type == "Business Leader"
		).order_by(Person.created_timestamp.asc())
	return object_list('bns_home.html',persons)


@bns_blueprint.route('/detail/')
def detail():

	return render_template('bns_detail.html')
	

cdt_parties/cdt_blueprint.py
from flask import Blueprint, url_for, render_template, request, redirect, flash, g
from models import Person

cdt_blueprint = Blueprint('cdt_parties',__name__,template_folder='templates')

def object_list(template,query):

	if request.args.get('q'):
		search = request.args['q']
		query = query.filter(Person.name.contains(search))
	return render_template(template,persons=query)

@cdt_blueprint.route('/')
def cdt_home():

	persons = Person.query.filter(
		Person.person_type == "cdt_parties"
		).order_by(Person.created_timestamp.desc())

	return object_list('cdt_home.html',persons)

@cdt_blueprint.route('/detail/')
def detail():

	return render_template("cdt_detail.html")

cele/cele_blueprint.py
from flask import Blueprint, url_for, render_template, request, redirect, flash, g
from models import Person

cele_blueprint = Blueprint('cele',__name__,template_folder='templates')


def object_list(template,query):

	if request.args.get('q'):
		search = request.args['q']
		query = query.filter(Person.name.contains(search))
	return render_template(template,persons=query)



@cele_blueprint.route('/')
def cele_home():
	return render_template('cele_list.html')

@cele_blueprint.route('/<person_type>')
def cele_list(person_type):

	# persons = Person.query.filter_by(person_type = person_type)

	persons = Person.query.filter(
		Person.person_type == person_type
		).order_by(Person.created_timestamp.desc())


	return object_list('cele_home.html',persons)

main.py
from app import app,db 
import views
import models 
import admin

# from cfp.cfp_blueprint import cfp
# app.register_blueprint(cfp,url_prefix='/cfp/')

from bns_leader.bns_blueprint import bns_blueprint
app.register_blueprint(bns_blueprint,url_prefix='/bns/')

from cdt_parties.cdt_blueprint import cdt_blueprint
app.register_blueprint(cdt_blueprint,url_prefix='/cdt/')

from cele.cele_blueprint import cele_blueprint
app.register_blueprint(cele_blueprint,url_prefix='/cele/')

from mb_pmt.mb_blueprint import mb_blueprint
app.register_blueprint(mb_blueprint,url_prefix='/mb/')

from modern_figures.modern_blueprint import modern_blueprint
app.register_blueprint(modern_blueprint,url_prefix='/modern_figures/')

if __name__ == '__main__':
    app.run()

mb_pmt/mb_blueprint.py
from flask import Blueprint, url_for, render_template, request, redirect, flash, g
from models import Person
mb_blueprint = Blueprint('mb_pmt',__name__,template_folder='templates')


def object_list(template,query):

	if request.args.get('q'):
		search = request.args['q']
		query = query.filter(Person.name.contains(search))
	return render_template(template,persons=query)


@mb_blueprint.route('/')
def mb_home():
	persons = Person.query.filter(
		Person.person_type == "mb_pmt"
		).order_by(Person.created_timestamp.asc())
	return render_template('mb_home.html',persons=persons)


@mb_blueprint.route('/detail/')
def detail():
	return render_template('mb_detail.html')

modern_figures/modern_blueprint.py
from flask import Blueprint, url_for, render_template, request, redirect, flash, g
from models import Person

modern_blueprint = Blueprint('modern_figures',__name__,template_folder='templates')


@modern_blueprint.route('/')
def modern_home():

	persons = Person.query.filter_by(person_type = "modern_figures")
	return render_template('modern_home.html',persons=persons)


@modern_blueprint.route('/detail/')
def detail():
	return render_template("modern_detail.html")

views.py
from app import app 
from flask import render_template , request
from config import Configuration
from models import Person 


def object_list(template,query):

	if request.args.get('q'):
		search = request.args['q']
		query = query.filter(Person.name.contains(search))
	return render_template(template,persons=query)


@app.route('/')
def home():

	# persons = Person.query.all()
	persons = Person.query.order_by(Person.created_timestamp.desc())
	return object_list('home.html',persons)



@app.route('/contact')
def contact():
	return render_template('contact.html')


@app.route('/about')
def about():
	return render_template('about.html')

@app.route('/news')
def news():
	return render_template('latest.html')


@app.route('/detail/<slug>')
def detail(slug):

	person = Person.query.filter_by(slug=slug).first_or_404()
	return render_template('detail.html',person=person)

bns_leader/templates/bns_base.html
{% extends 'base.html' %}

bns_leader/templates/bns_home.html
{% extends "bns_base.html" %}
{% from "macro/display_person.html" import display_person %}

{% block content_title %}Business Leader{% endblock %}

{% block content_search %}
	
	{% include "include/add_search.html" %}

{% endblock %}

{% block content_main %}

	{{ display_person(persons) }}	

{% endblock %}

cdt_parties/templates/cdt_base.html
{% extends "base.html" %}

cdt_parties/templates/cdt_home.html
{% extends "cdt_base.html" %}
{% from "macro/display_person.html" import display_person %}

{% block content_title %}Candidate from Parties{% endblock %}


{% block content_search %}
	
	{% include "include/add_search.html" %}

{% endblock %}

{% block content_main %}

	{{ display_person(persons) }}	

{% endblock %}

cele/templates/cele_base.html
{% extends "base.html" %}

cele/templates/cele_home.html
{% extends "cele_base.html" %}
{% from "macro/display_person.html" import display_person %}
{% block content_title %}Celebrities{% endblock %}

{% block content_search %}
	
	{% include "include/add_search.html" %}

{% endblock %}

{% block content_main %}

	{{ display_person(persons) }}

{% endblock %}

cele/templates/cele_list.html
{% extends "cele_base.html" %}
{% block content_title %}Celebrities{% endblock %}

{% block content_main %}

	
	<!--Grid row-->
            <div class="row wow fadeIn">

                <!--Grid column-->
                <div class="col-lg-12 col-md-6 mb-12">

                        <!--Card-->
                    <div class="card">
                            <a href="{{ url_for('cele.cele_list',person_type='Model') }}" 
                            class="list-group-item d-flex justify-content-between align-items-center">
                                <b>Models</b>
                                <span class="badge badge-primary badge-pill">14</span>
                            </a>
                            <a href="{{ url_for('cele.cele_list',person_type='Actor') }}" 
                            class="list-group-item d-flex justify-content-between align-items-center">
                                <b>Actors</b>
                                <span class="badge badge-primary badge-pill">2</span>
                            </a>
                            <a href="{{ url_for('cele.cele_list',person_type='Actress') }}" 
                            class="list-group-item d-flex justify-content-between align-items-center">
                                <b>Actress</b>
                                <span class="badge badge-primary badge-pill">2</span>
                            </a>
                            <a href="{{ url_for('cele.cele_list',person_type='Director') }}" 
                            class="list-group-item d-flex justify-content-between align-items-center">
                                <b>Directors</b>
                                <span class="badge badge-primary badge-pill">1</span>
                            </a>
                            <a href="{{ url_for('cele.cele_list',person_type='Vocalist') }}" 
                            class="list-group-item d-flex justify-content-between align-items-center">
                                <b>Vocalist</b>
                                <span class="badge badge-primary badge-pill">1</span>
                            </a>
                            
                    </div>

                </div>
                <!--Grid column-->

            </div>

{% endblock %}

mb_pmt/templates/mb_base.html
{% extends 'base.html' %}

mb_pmt/templates/mb_home.html
{% extends "mb_base.html" %}
{% from "macro/display_person.html" import display_person %}

{% block content_title %}Member of Patliment{% endblock %}

{% block content_search %}
	
	{% include "include/add_search.html" %}

{% endblock %}

{% block content_main %}

	{{ display_person(persons) }}	

{% endblock %}

modern_figures/templates/modern_base.html
{% extends 'base.html' %}

modern_figures/templates/modern_home.html
{% extends "modern_base.html" %}
{% from "macro/display_person.html" import display_person %}

{% block content_title %}Modern Historical Figures{% endblock %}

{% block content_search %}
	
	{% include "include/add_search.html" %}

{% endblock %}

{% block content_main %}

	{{ display_person(persons) }}	

{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>who is Who in Myanmar</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{{ url_for('static',filename='css/mdb.min.css') }}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{{ url_for('static',filename='css/style.min.css') }}" rel="stylesheet">

    <link href="{{ url_for('static',filename='js/style.js') }}" rel="stylesheet">
    <script type="text/javascript">
        $(document).ready(function () {
            $('#dtBasicExample').DataTable();
            $('.dataTables_length').addClass('bs-select');
        });
    </script>


    <!-- Disable tap highlight on IE -->
    <meta name="msapplication-tap-highlight" content="no">

    <!-- Web Application Manifest -->
    <!-- <link rel="manifest" href="manifest.json"> -->


    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Web Starter Kit">
    <link rel="icon" sizes="192x192" href="{{ url_for('static',filename='img/wwm.png') }}">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Web Starter Kit">
    <link rel="apple-touch-icon" href="{{ url_for('static',filename='img/wwm.png') }}">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" 
        content="{{ url_for('static',filename='img/wwm.png') }}">
    <meta name="msapplication-TileColor" content="#2F3BA2">

    <!-- Color the status bar on mobile devices -->
    <meta name="theme-color" content="#2F3BA2">


</head>
<body class="grey lighten-3">
    
    <div class="container-fluid mt-5">

            
            <!--Grid row-->
            
            <!--Grid row-->

            <!-- Editable table -->
            <div class="card">
                        <h3 class="card-header text-center font-weight-bold py-4">About Team Roles</h3>
                        <div class="card-body">
                            <div id="table" class="table-editable">
                                <span class="table-add float-right mb-3 mr-2"><a href="#!" class="text-success"></a></span>
                                <table class="table table-bordered table-responsive-md table-striped text-center">
                                    <tr>
                                        <th class="text-center">Name</th>
                                        <th class="text-center">Role</th>
                                        <th class="text-center">Skills&Requirements</th>
                                    </tr>
                                    <tr>
                                        <td class="pt-3-half" contenteditable="true">Mg Thura Aung</td>
                                        <td class="pt-3-half" contenteditable="true">Team Lead</td>
                                        <td class="pt-3-half text-justify" contenteditable="true">General Passion for all the technologies invovled in creating software. Specific skill and expertise in at least one role is a requirement and is also responsible for monitoring, reporting and proper and timely project execution</td>
                                    </tr>
                                    <!-- This is our clonable table line -->
                                    <tr>
                                        <td class="pt-3-half" contenteditable="true">Ma Wint Theingi Hlaing</td>
                                        <td class="pt-3-half" contenteditable="true">UIUX Lead</td>
                                        <td class="pt-3-half text-justify" contenteditable="true">Passtion for design and userability. Someone who can think like a normal user. In this program he/she must have skills in HTML/CSS/JS and must learn a few frameworks such as BootStrap, Material Design, Angular and so on. Use of graphics tools and mockup tools</td>
                                    </tr>
                                    <!-- This is our clonable table line -->
                                    <tr>
                                        <td class="pt-3-half" contenteditable="true">Ma Sandar Win</td>
                                        <td class="pt-3-half" contenteditable="true">UIUX Dev</td>
                                        <td class="pt-3-half text-justify" contenteditable="true">Passtion for design and userability. Someone who can think like a normal user. In this program he/she must have skills in HTML/CSS/JS and must learn a few frameworks such as BootStrap, Material Design, Angular and so on. Use of graphics tools and mockup tools</td>
                                    </tr>
                                    <!-- This is our clonable table line -->
                                    <tr class="hide">
                                        <td class="pt-3-half" contenteditable="true">Ma Yadanar Win</td>
                                        <td class="pt-3-half" contenteditable="true">Dev 1</td>
                                        <td class="pt-3-half text-justify" contenteditable="true">Good logical thinking skill. Confortable with writing and rewriting code and reading and learning from other devs code. Either dev one or two must write code for Unit Test as well</td>
                                    </tr>

                                    <tr class="hide">
                                        <td class="pt-3-half" contenteditable="true">Ma Su Myat Phyo</td>
                                        <td class="pt-3-half" contenteditable="true">Dev 2</td>
                                        <td class="pt-3-half text-justify" contenteditable="true">Good logical thinking skill. Confortable with writing and rewriting code and reading and learning from other devs code.</td>
                                    </tr>

                                    <tr class="hide">
                                        <td class="pt-3-half" contenteditable="true">Mg Kaung Htet Aung</td>
                                        <td class="pt-3-half" contenteditable="true">Test and Documentation</td>
                                        <td class="pt-3-half text-justify" contenteditable="true">Have clear and conciese writing skills. Understands the value of documention.</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
            </div>
<!-- Editable table -->
       
           
            
        </div>


        <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="js/jquery-3.3.1.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="js/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="js/mdb.min.js"></script>
    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();
    </script>

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8">
        <meta name="description" content="">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    	<meta http-equiv="x-ua-compatible" content="ie=edge">
    	<title>{% block content_title %}{% endblock %}</title>
    	<!-- Font Awesome -->
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    	<!-- Bootstrap core CSS -->
    	<link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    	<!-- Material Design Bootstrap -->
    	<link href="{{ url_for('static',filename='css/mdb.min.css') }}" rel="stylesheet">
    	<!-- Your custom styles (optional) -->
    	<link href="{{ url_for('static',filename='css/style.min.css') }}" rel="stylesheet">

        <!-- Disable tap highlight on IE -->
        <meta name="msapplication-tap-highlight" content="no">

        <!-- Add to homescreen for Chrome on Android -->
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="application-name" content="Web Starter Kit">
        <link rel="icon" sizes="192x192" href="{{ url_for('static',filename='img/wwm.png') }}">

        <!-- Add to homescreen for Safari on iOS -->
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-title" content="Web Starter Kit">
        <link rel="apple-touch-icon" href="{{ url_for('static',filename='img/wwm.png') }}">

        <!-- Tile icon for Win8 (144x144 + tile color) -->
        <meta name="msapplication-TileImage" content="{{ url_for('static',filename='img/wwm.png') }}">
        <meta name="msapplication-TileColor" content="#2F3BA2">

        <!-- Color the status bar on mobile devices -->
        <meta name="theme-color" content="#2F3BA2">

	</head>	
	<body>		
		<!--Main Navigation-->
    <header>               
        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
                    <div class="container-fluid">

                        <!-- Brand -->
                        <a class="navbar-brand waves-effect" href="#">
                            <!-- <strong class="blue-text">WWM</strong> -->
                        </a>
                        <a class="navbar-brand waves-effect" href="#">
                            <!-- <strong class="blue-text">WWM</strong> -->
                        </a>

                        <!-- Collapse -->
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="true" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <!-- Links -->
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">

                            <!-- Left -->
                            <ul class="navbar-nav mr-auto nav nav-tabs">
                                <li class="nav-item active">
                                    <a class="nav-link waves-effect" href="{{ url_for('home') }}">Home
                                        <span class="sr-only">(current)</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link waves-effect" 
                                    href="{{ url_for('news') }}">News</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link waves-effect" 
                                        href="{{ url_for('about') }}">
                                    About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link waves-effect" href="{{ url_for('contact') }}">Contact</a>
                                </li>
                            </ul>

                            {% block content_search %}{% endblock %}
                            

                    <!-- Right -->
                    <ul class="navbar-nav nav-flex-icons">
                        <li class="nav-item">
                            <a href="#" class="nav-link waves-effect">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link waves-effect">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link waves-effect">
                                <i class="fa fa-linkedin"></i>
                            </a>
                        </li>
                        <!-- <li class="nav-item">
                            <a href="#" class="nav-link border border-light rounded waves-effect">
                                <i class="fa fa-github mr-2"></i>HWM GitHub
                            </a>
                        </li> -->
                    </ul>

                </div>
            </div>
        </nav>
        <!-- Navbar -->

        <!-- Sidebar -->
        <div class="sidebar-fixed position-fixed">

            <a class="logo-wrapper waves-effect">
                <img src="{{ url_for('static',filename='img/wwm.png') }}" 
                class="img-fluid" alt="" style="width:150px;height:150px;">
            </a>

            <div class="list-group list-group-flush">
                <!-- <a href="#" class="list-group-item active waves-effect">
                    <i class="fa fa-dashboard mr-3"></i>Dashboard
                </a> -->
                <a href="{{ url_for('cdt_parties.cdt_home') }}" 
                class="list-group-item list-group-item-action waves-effect">
                    <i class="fa fa-users indigo-text mr-3"></i>Candidates from Parties</a>
                <a href="{{ url_for('mb_pmt.mb_home') }}"
                 class="list-group-item list-group-item-action waves-effect">
                    <i class="fa fa-users indigo-text mr-3"></i>Members of Parliaments</a>
                <a href="{{ url_for('bns_leader.bns_home') }}" 
                class="list-group-item list-group-item-action waves-effect">
                    <i class="fa fa-users indigo-text mr-3"></i>Business Leaders</a>
                <a href="{{ url_for('cele.cele_home') }}" 
                class="list-group-item list-group-item-action waves-effect">
                    <i class="fa fa-users indigo-text mr-3"></i>Celebrities</a>
                <a href="{{ url_for('modern_figures.modern_home') }}" 
                class="list-group-item list-group-item-action waves-effect">
                    <i class="fa fa-users indigo-text mr-3"></i>Modern Historical Figures</a>
            </div>

        </div>
        <!-- Sidebar -->

    </header>
    <!--Main Navigation-->

    <!--Main layout-->
    <main class="pt-5 mx-lg-5">
        <div class="container-fluid mt-5">           

        	{% block content_main %}{% endblock %}
        </div>
    </main><br><br><br><br><br><br><br><br><br><br>
    <!--Main layout-->


    	<!--Footer-->
    <footer class="page-footer text-center font-small mdb-color darken-2 mt-4 wow fadeIn">   
        <!--Copyright-->
        <div class="footer-copyright py-3">
            © 2018 Copyright:
            <a href="#"> Odin-Mdy-Geo.com </a>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->


	<!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" 
    src="{{ url_for('static',filename='js/jquery-3.3.1.min.js') }}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{{ url_for('static',filename='js/popper.min.js') }}">
    </script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{{ url_for('static',filename='js/bootstrap.min.js') }}">
    </script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{{ url_for('static',filename='js/mdb.min.js') }}">
    </script>
    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();
    </script>
	</body>

</html>

templates/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Material Design Bootstrap</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{{ url_for('static',filename='css/mdb.min.css') }}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{{ url_for('static',filename='css/style.min.css') }}" rel="stylesheet">
</head>

<body>
    
    

    <div class="container mt-5">

         
         <!-- Heading -->
            <div class="card mb-4 wow fadeIn">


                <!--Card content-->
                <div class="card-body d-sm-flex justify-content-between">                    

                    <h4 class="mb-2 mb-sm-0 pt-1">
                        <h4>
                                <b>Biography In Detail</b>
                            
                        </h4>
                    </h4>
                    <form class="d-flex justify-content-left">                       
                        

                    </form>

                </div>

            </div>
    <!-- Heading -->   
            <!--Grid row-->
            
            <!--Grid row-->

            <!--News card-->
<div class="card mb-3 text-center hoverable">
    <div class="card-body">
        <!--Grid row-->
        <div class="row pt-2 wow fadeIn">

            <!--Grid column-->
            <div class="col-md-4 offset-md-1 mx-3 my-3">
                <!--Featured image-->
                <div class="view overlay">
                    <img 
                    src="{{ url_for('static',filename='img/'+person.image_id) }}" 
                    alt="" 
                    class="img-fluid">
                    <a>
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-7 text-left ml-3 mt-3">
                <!--Excerpt-->
                
                <h3 class="font-weight-bold text-left mb-3 dark-grey-text">
                {{ person.name }}</h3>
                <p class="text-justify">
                    {{ person.biography }}
            </p>
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->
    </div>
</div>
<!--News card-->
       
           
            
        </div>


        <br><br><br><br><br><br><br><br><br><br>
    <!--Footer-->
    <footer class="page-footer text-center font-small mdb-color darken-2 mt-4 wow fadeIn">   
        <!--Copyright-->
        <div class="footer-copyright py-3">
            © 2018 Copyright:
            <a href="#"> Odin-Mdy-Geo.com </a>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->


    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" 
      src="{{ url_for('static',filename='js/jquery-3.3.1.min.js') }}">
    </script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{{ url_for('static',filename='js/popper.min.js') }}">
    </script>

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>

    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{{ url_for('static',filename='js/mdb.min.js') }}">
    </script>

    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();
    </script>

    
</body>

</html>

templates/include/add_search.html
<!-- Search form -->
    <form class="form-inline" method="get" role="form">
    	<input class="form-control" 
    	type="text" 
    	placeholder="Search" 
    	aria-label="Search"
    	name="q" vlaue="{{ request.args.get('q', '') }}"
    	>
    </form>
<!-- Search form -->